CREATE TABLE audit_trails (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    user_id int8 NOT NULL,
    user_email varchar(100) NOT NULL,
    user_name varchar(100) NOT NULL,
    user_role varchar(100) NOT NULL,
    action varchar(150) NOT NULL,
    url varchar(255) NOT NULL,
    request_id varchar(100) NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT audit_trails_pkey PRIMARY KEY (id)
);
CREATE INDEX audit_trails_action_idx ON audit_trails USING btree ("action");