CREATE TYPE admin_statuses AS ENUM ('active','inactive');
CREATE TABLE admins (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	email varchar(100) NOT NULL,
	full_name varchar(100) NULL,
	password_hash varchar(255) NOT NULL,
	created_at timestamp NULL DEFAULT now(),
	created_by int8 NOT NULL,
	updated_at timestamp NULL,
	updated_by int8 NULL,
	deleted_at timestamp NULL,
	deleted_by int8 NULL,
	role_id int8 NOT NULL,
	status admin_statuses NOT NULL DEFAULT 'active'::admin_statuses,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE UNIQUE INDEX admins_email_idx ON admins USING btree (email);